### ISSUE TITLE
PADV Change with changed MTP not possible: The 'hl7:repeatNumber' is forbidden in the 'Changed Dosage Instructions' part of PADV items.

### ISSUE THREAD

**Issue by ziegm** [ahdis/ch-emed-pmp#20]
@oliveregger : Could you please adapt the mapping?

UC:
[MTP Cetirizine](http://build.fhir.org/ig/ahdis/ch-emed-pmp/Bundle-3-1-MTPCetirizine.json.html)
[PADV Cetirizine (CHANGE)](http://build.fhir.org/ig/ahdis/ch-emed-pmp/Bundle-3-2-PADVCetirizine.json.html)

Transformed CDA document: 
[CDA-3-2-PADVCetirizine.zip](https://github.com/ahdis/ch-emed-pmp/files/9357693/CDA-3-2-PADVCetirizine.zip) with forbidden element: `<repeatNumber nullFlavor="NI"/>`
[CDA spec (Art decor)](https://art-decor.org/art-decor/decor-templates--cdachemed-?section=templates&id=2.16.756.5.30.1.1.10.4.34&effectiveDate=2019-12-11T11:31:52&language=en-US)

Provide and register:
```json
	
{
  "response": {
    "status": 400,
    "data": {
      "resourceType": "OperationOutcome",
      "issue": [
        {
          "severity": "error",
          "code": "invalid",
          "details": {
            "coding": [
              {
                "code": "INVALID_DOCUMENT_CONTENT"
              }
            ],
            "text": "The document 'f761dbf7-c05c-46bf-9b2a-94ca58d8b374' is not valid: Schematron error: {[[Text@0x79c93037: content=[(PharmaceuticalAdviceItemEntryContentModule): The 'hl7:repeatNumber' is forbidden in the 'Changed Dosage Instructions' part of PADV items.]]; fpi=null; icon=null; lang=null; see=null; space=null]} in {/hl7:ClinicalDocument/hl7:component/hl7:structuredBody/hl7:component/hl7:section/hl7:entry/hl7:observation/hl7:entryRelationship[2]/hl7:substanceAdministration}."
          }
        }
      ]
    }
  },
  "config": {
    "method": "POST",
    "url": "https://test.ahdis.ch/mag-pmp/fhir/",
    "headers": {}
  }
}
```

**Comment by oliveregger** [comment]
I think this schematron error triggers wrongly. this should be a change of the MTP (following this example in the spec
http://fhir.ch/ig/ch-emed/pharmaceutical-advice-document.html#modifying-an-existing-medication), correct @ziegm ? 

>Number of repeats/refills. Either the @value or @nullFlavor attribute shall be set. It's required in MTP, PRE and PADV 
>(changed MTP, changed/recommended PRE) items ; forbidden in DIS and PADV (changed dosage instructions) items.

We have PADV with a changed MTP and this should be ok to have repeatNumber set (see comment above for changed mtp). However it looks like the schematron triggers also because the changed MedicationStatement has also the  templateId root="1.3.6.1.4.1.19376.1.9.1.3.6"

<img width="1244" alt="image" src="https://user-images.githubusercontent.com/2414516/185089061-05a108f3-ec64-4461-a0fa-0174ec88c36f.png">

@qligier could you have a look?

**Comment by qligier** [comment]
Yep, the schematron rule is leaking here, that should be correct. I've opened https://art-decor.org/art-decor/decor-issues--cdachemed-?id=2.16.756.5.30.1.127.77.12.6.32

**Comment by qligier** [comment]
I've deployed a patch, I hope it's sufficient. It's a mess to fix in the generated Schematron, hope it'll be easier to fix in ArtDecor.
